Styling the index page with article cards
CraftAcademy/The-Ultras-Newsroom-JAN-2019- pull request #12
Opened 2019-03-18 10:03 UTC by nevroje

#### PT Story: https://www.pivotaltracker.com/story/show/164660590
#### Description
 Articles as cards
Hover effect on cards
Hover effect shows lead
We had to reinstall tailwind

#### What I have learned working on this feature: 
How to use a "hidden" hover effect so that lead/content only shows when hovering over that specific card.
#### Screenshots:

## Index: 
![image](https://user-images.githubusercontent.com/45144030/54521937-5140af00-496c-11e9-8e2f-8bf92e625d28.png)
## Hover: (if gif is not working here is the link https://gyazo.com/2359c7fab7ae3a445b1e56b8dfaca9b9 ) 
![hover](https://user-images.githubusercontent.com/45144030/54522171-db891300-496c-11e9-88be-a2d0a37ae2cc.gif)

2019-03-18 10:15 UTC, magnus-thor requested changes

2019-03-18 10:15 UTC, magnus-thor commented on coverage/.resultset.json
> +{
Coverage folder should be in gitignore

2019-03-18 12:52 UTC, aleciabenjamin commented on app/javascript/css/application.css
> +
extra line

2019-03-18 12:55 UTC, NiciP commented on config/environments/development.rb
> +  # Verifies that versions and hashed value of the package contents in the project's package.json
Need to remove comments here?

2019-03-18 12:55 UTC, NiciP commented on config/environments/development.rb
>    # Settings specified here will take precedence over those in config/application.rb.
Need to remove comments here?

2019-03-18 12:55 UTC, NiciP approved these changes

2019-03-19 14:54 UTC, magnus-thor requested changes

2019-03-19 14:54 UTC, magnus-thor commented on app/javascript/css/application.css
> +
Remove this file

2019-03-19 14:54 UTC, magnus-thor commented on app/javascript/css/tailwind.css
> +    margin-left: 25px;
this can be change to `@apply ml-6;`

2019-03-19 14:54 UTC, magnus-thor commented on app/views/articles/index.html.erb
> +    <div id="#{dom_id(article)}">
Change this to `<div id="<%= dom_id(article) %>">`

2019-03-19 15:28 UTC, magnus-thor approved these changes

2019-03-19 15:29 UTC, merged