Language translation update
CraftAcademy/The-Ultras-Newsroom-JAN-2019- pull request #18
Opened 2019-03-25 13:29 UTC by perhegg

#### [PT Story: Language translation update](https://www.pivotaltracker.com/story/show/164846583)

As a development team
In order to have a understandable user interface
I would like to add language translation to the page

#### Description
Changes proposed in this pull request:

* Adds swedish translation to the page

#### What I have learned working on this feature: 
I have learn't how to add nested translations and how to select them correctly from the element.

2019-03-26 08:20 UTC, yanqiuzhang approved these changes

2019-03-26 08:24 UTC, NiciP approved these changes

2019-03-26 08:55 UTC, magnus-thor requested changes

2019-03-26 08:55 UTC, magnus-thor commented on db/seeds.rb
> +article_1 = Article.create(title: "Voted best mead recipe", lead: "Restaurant wins prize", content: "Restaurant wins prize for best mead in Sweden", user_id: 1)
dont hard code the ids for the user.

2019-03-27 08:15 UTC, perhegg commented on db/seeds.rb
> +article_1 = Article.create(title: "Voted best mead recipe", lead: "Restaurant wins prize", content: "Restaurant wins prize for best mead in Sweden", user_id: 1)
done

2019-03-27 08:50 UTC, magnus-thor approved these changes
Good job

2019-03-27 08:54 UTC, merged